### ISSUE TITLE
Create other issue type

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/.github#5]
I think the issue and PR templates are good for some uses. However, in general, I would like to be able to create an issue or PR without clutter. Please add a "general" or "other" 
- [ ] issue template AND 
- [ ] pull request template
that allows the creation of tasks without prefilled text.

**Comment by Hyper-Node** [comment]
For issues, there is a  "Don’t see your issue here? Open a blank issue."-button in the issue creation dialogue.

**Comment by physikerwelt** [comment]
OK. Sorry, I did not see that.

**Comment by Hyper-Node** [comment]
Created one blank MaRDI blank issue with minimal header. For the pr-templates, I would just stick to it like it is, since multiple pr-templates from PULL_REQUEST_TEMPLATES folder won't appear when creating pr-request.
